language: node_js
node_js:
  - 8
  - 10
  - 12
os:
  - linux

script:
  - "npm run lint"
  - "npm run cover"

after_success:
  - if [[ $TRAVIS_NODE_VERSION == "12" ]]; then cat ./coverage/lcov.info | coveralls; fi
